### PR TITLE
Requested by Ryal and KGR

### PR DESCRIPTION
**Pull request by TMinusBlastedRocket**
ryal and kgr said it was a good idea, and it does compile

### CODE REVIEW

**Comment by WiiBeep** [comment]
hmm yes

**Comment by TMinusBlastedRocket** [comment]
> ryal and kgr said it was a good idea, and it does compile

**Comment by WiiBeep** [comment]
WHY DID U CLOSE IT I AM ANGERY >:[

**Comment by TMinusBlastedRocket** [comment]
> WHY DID U CLOSE IT I AM ANGERY >:[

misinput

**Comment by GamerKGR** [comment]
i am kgr and i approve of this message

**Comment by GamerKGR** [comment]
> > WHY DID U CLOSE IT I AM ANGERY >:[
> 
> misinput

L

**Comment by TMinusBlastedRocket** [comment]
> > > WHY DID U CLOSE IT I AM ANGERY >:[
> > 
> > 
> > misinput
> 
> L

you like the change? its just like what you said in vc

**Comment by GamerKGR** [comment]
> > > > WHY DID U CLOSE IT I AM ANGERY >:[
> > > 
> > > 
> > > misinput
> > 
> > 
> > L
> 
> you like the change?

sketch is my daddy

**Comment by WiiBeep** [comment]
> > > > WHY DID U CLOSE IT I AM ANGERY >:[
> > > 
> > > 
> > > misinput
> > 
> > 
> > L
> 
> you like the change? its just like what you said in vc

yes

**Comment by TMinusBlastedRocket** [comment]
> > > > > WHY DID U CLOSE IT I AM ANGERY >:[
> > > > 
> > > > 
> > > > misinput
> > > 
> > > 
> > > L
> > 
> > 
> > you like the change? its just like what you said in vc
> 
> yes

of course

**Comment by TMinusBlastedRocket** [comment]
This is the best feature to ever be coded in to this bot

**Comment by TMinusBlastedRocket** [comment]
this is a bucket

**Comment by GamerKGR** [comment]
> This is the best feature to ever be coded in to this bot

the best feature of wiilink bot is here

**Comment by noahpistilli** [comment]
This is not a nice joke

**Pull request closed without merging**
